#port
server:
   port: 80
#database application-datasource.xml
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/mydb?autoReconnection=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      database: mysql
      properties:
         hibernate:
           dialect: org.hibernate.dialect.MySQLDialect
           storage_engin: innodb
           show_sql: true
           format_sql: true
           user_sql_comments: true

